name: Playwright test

on:
 #workflow_dispatch:
 schedule:
  - cron: "*/15 * * * *"

env:
    fetchUrl: ${{ secrets.FETCH_URL }}
    postUrl: ${{ secrets.POST_URL }}
    
jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn
      - name: Install playwright browser
        run: npx playwright install chromium
      - name: Run tests
        run: npx playwright test 
